addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - oraclejdk8
notifications:
  slack: ftsrg:4L2WFnNwpMjl9jtbqKCfy2dh
  on_success: change
<<<<<<< HEAD
  on_failure: always
=======
  on_failure: always

env:
  global:
    secure: "WG6uXkr/+nEzgsQ/VoxJenIb23yTqBQoR7qgq3QliBND1JZ3wHLU9/dycHaYhLhEouSjHFVazImNISFOrasD6v1vWCfjQzbcGHWBpfG3MrwfBEXw3si8FnDHGWwJSPv5/3M19EUuoJdWsey3zGoi0ot84i85c72b9g/XvmJuf41sHJCf4tUbpjj6LxY7Ln+Uo0IE/H/7s2fkEGA6kG7bMxAnJypkX6iPOrHnLDYVlJXSlEDEWZAD2aoVUSJ6oNtXRnZUVhvDyxenWtgeU7Z43NZnfZ6aFyTadwSdGRKi9M41MHCK6AYcXjTnArcFjjCmK7dESXQYt3yOND58lU5gsmrGzp31PLL4RRcKP40yaALxjoWlm7k/i3hJGKv26LZWcdtCRQve224OmjHy0N5jGLlnGhmDGiqgi6zbJ6BAOPCRGbWVAt4oVUT/qssUN7nyhkBEEvA/pVRbyBtdX3kStbdlmFg4gavvtDzCSCq5CocClnYsmhXPerZ0ADQpWl9x/lRpbaJJK0AomaARVbhee7ZX286hK5YwEddB/CcKK5LMhIksLfZNph5HRe/7otYD+tzUNm5mYljreypYjN3JHahaUu/5OVCdfLvKAkXHb0B7a/dyImOLlt0Gc1A5FD0/bXBV2qMpU/AkN782Y3NYcV/IW4ugYOai5Tdp/6Yc+0s="

script:
  ./gradlew jacocoRootReport

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
>>>>>>> upstream/master
